version: '3'
services:
  hadoop-node:
    build: .
    container_name: hadoop-node
    ports:
      - "9870:9870"   # NameNode UI
      - "8088:8088"   # YARN ResourceManager UI
    volumes:
      - ./data:/data
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - .:/workspace
      - ./cleansed_output.txt:/workspace/cleansed_output.txt
    tty: true
